forum/urls.py
from django.conf.urls import url, include
from django.contrib import admin

import views
from usercenter.views import activate


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^article/', include('article.urls')),
    url(r'^comment/', include('comment.urls')),
    url(r'^message/', include('message.urls')),
    url(r'^usercenter/', include('usercenter.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^register$', views.register),
    url(r'^activate/(?P<code>\w+)$', activate),
    url(r'^$', views.index),
]

# admin.site.disable_action('delete_selected')

usercenter/models.py
from django.contrib.auth.models import User
from django.db import models


class ActivateCode(models.Model):
    owner = models.ForeignKey(User, verbose_name="用户")
    code = models.CharField("激活码", max_length=100)

    expire_timestamp = models.DateTimeField()

    create_timestamp = models.DateTimeField(auto_now_add=True)
    last_update_timestamp = models.DateTimeField(auto_now=True)


class UserProfile(models.Model):
    user = models.OneToOneField(User,
            on_delete=models.CASCADE)
    sex = models.IntegerField("性别",
            choices=((0, "男"), (-1, "女")),
            default=0)
    birthday = models.DateTimeField("生日",
            null=True, blank=True)
    avatar = models.CharField("头像", max_length=300, blank=True)

templates/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>论坛首页</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
  </head>
  <body>
    <div class="container">
    	<div class="row">
        <div class="col-xs-12 col-md-12">
          <div class="jumbotron">
            <center><h1>Python部落论坛</h1></center>
          </div>
        </div>
      </div>
    	<div class="row">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="col-xs-12 col-md-10">
  {% for b in blocks %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <a href="/article/list/{{ b.id }}" style="font-size: 16px;">{{ b.name }}</a>
      <span class="pull-right">{{ b.manager }}</span>
    </div>
    <div class="panel-body">
      {{ b.desc }}
    </div>
  </div>
  {% endfor %}
</div>
<div class="col-xs-12 col-md-2">
  <div class="well">
    {% if user.is_authenticated %}  
      <p>
        {% if user.userprofile.avatar %}
          <img src="{{ user.userprofile.avatar }}" style="width: 100%; height: 150px;" alt="头像" />
        {% else %}
          <a href="/usercenter/uploadavatar/">您还没有头像，去上传</a>
        {% endif %}
        {{ user.username }}({{ user.userprofile.get_sex_display }}). 欢迎来到论坛.
        {% if msg_cnt %}
        <a href="/message/list"><span class="badge">{{ msg_cnt }}</span></a>
        {% endif %}
      </p>
      <a href="/accounts/logout">登出</a>&nbsp;<a href="/accounts/password_change/">修改密码</a>
    {% else %}               
      <p>匿名用户. 请<a href="/accounts/login">登录</a>.</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-3">
     &nbsp;
    </div>
    <div class="col-md-6">
      {% if error %}
      <div class="alert alert-danger">{{ error }}</div>
      {% endif %}
      <div class="panel panel-info">
        <div class="panel-heading">
          <b>注册</b>
        </div>
        <div class="panel-body">
          <form method="post" action="">
          {% csrf_token %}
          
          <div class="input-group">
              <span class="input-group-addon">用户名</span>
              <input id="id_username" maxlength="254" name="username" type="text" class="form-control" />
          </div>
          <br />
          <div class="input-group">
              <span class="input-group-addon">邮箱&nbsp;&nbsp;&nbsp;&nbsp;</span>
              <input id="id_email" name="email" type="text" class="form-control" />
          </div>
          <br />
          <div class="input-group">
              <span class="input-group-addon">密码&nbsp;&nbsp;&nbsp;&nbsp;</span>
              <input id="id_password" name="password" type="password" class="form-control" />
          </div>
          <br />
          <div class="input-group">
              <span class="input-group-addon">确认密码</span>
              <input id="id_re_password" name="re_password" type="password" class="form-control" />
          </div>
          <br />
          <input type="submit" class="btn btn-primary" value="注册" />
          </form>
        </div>
        <div class="panel-footer">

        </div>
      </div>
    </div>
    <div class="col-md-3">
     &nbsp;
    </div>
  </div>
</div>
{% endblock %}

templates/success_hint.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-3">
 &nbsp;
</div>
<div class="col-md-6">
  <h2>{{ msg }}</h2>
  <a href="{{ link }}">{{ hint }}</a>
</div>
<div class="col-md-3">
 &nbsp;
</div>
{% endblock %}